application: vpsrvr
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: lxml
  version: latest

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /src
  static_dir: src
- url: .*
  script: main.py