application: vpsrvr
version: 1e
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: lxml
  version: latest
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /
  static_files: index.html
  upload: index\.html
- url: /src
  static_dir: src
- url: /.+
  script: main.application